### ISSUE TITLE
Change method of serving PWA from Docker to GitHub pages (or another solution)

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#158]
@kelson42 I guess you were referring to this news:

https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

I currently use GitHub pages on this repository to run an implementation from the `master` branch for testing. Were you suggesting that we set up a separate repository for a "clean" GitHub pages elsewhere, with the same domain: pwa.kiwix.org? I'm not sure if GitHub pages can serve more than one branch from a single repositroy (this one), which is what I'd need, one for the unreleased/non-production code, and one for production.

However, a second repository for production PWA code might be a solution.

It would be nice if pwa.kiwix.org could continue to function, so I don't have to do an emergency update of apps that leverage it! (Kiwix JS Windows, WikiMed, Wikivoyage).

**Comment by kelson42** [comment]
Then we will have to build the docker image in github and upload it. This is a move we have already started on many repos. Look fo example to worflow at openzim/mwoffliner.

**Comment by Jaifroid** [comment]
Can we use the GitHub Container registry? https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry It looks like they support open source public repositories.

**Comment by Jaifroid** [comment]
Is this the workflow to use as basis for one here? 
https://github.com/openzim/mwoffliner/blob/master/.github/workflows/docker.yml

**Comment by kelson42** [comment]
Yes. openzim/docker-publish-action has been created by @rgaudin to simplify the publication on both grcio and Docker hub. I think publishing on Docker hub shoukd be enough, but not sure this is supported.

**Comment by rgaudin** [comment]
> Yes. openzim/docker-publish-action has been created by @rgaudin to simplify the publication on both ghcr and Docker hub. I think publishing on Docker hub should be enough, but not sure this is supported.

Yes it's possible

**Comment by Jaifroid** [comment]
OK, thanks, so I've found @rgaudin's  helpful [documentation](https://github.com/openzim/docker-publish-action) on this action. @kelson42 can you add the secrets that will be needed to this Repo (or else send to me via PGP)? Or else provide me with whatever details I need so I can generate the secrets on dockerhub? NB This is for DockerHub image name `kiwix/kiwix-pwa`. Many thanks!

**Comment by kelson42** [comment]
@rgaudin can you please do that?

**Comment by rgaudin** [comment]
Added the four secrets (so it's harmonized with other repos, although I understand you won't push to GHCR for now)

Your workflow could look like this ; but please double-check.

```yaml
name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@v5
        with:
          image-path: kiwix/kiwix-pwa
          tag-pattern: /^v([0-9.]+).*$/
          latest-on-tag: true
          dockerfile: Dockerfile.pwa
          restrict-to: kiwix/kiwix-js-windows
          registries: docker.io
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
```
